version: '3.1'

volumes:
  pg_data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - data_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://data_db:5432/data_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  data_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=data_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"