spring.application.name=spring-docker


spring.datasource.url=jdbc:postgresql://localhost:5433/data_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
